server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    #      uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
  main:
    web-application-type: reactive

  config:
    import: "optional:configserver:"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
